// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMKP92g8XkkgjdLAnC3FBDBTFn5KreEN4',
    appId: '1:147455817597:web:50c9044f314c76ba26be14',
    messagingSenderId: '147455817597',
    projectId: 'koo-pai',
    authDomain: 'koo-pai.firebaseapp.com',
    storageBucket: 'koo-pai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfNLw3wsVWYPS0CesrWuqwfQWbD1UyqgU',
    appId: '1:147455817597:android:b4cad5c19f449bf626be14',
    messagingSenderId: '147455817597',
    projectId: 'koo-pai',
    storageBucket: 'koo-pai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJOlVYR2Fn0GlYBqhbbYv363STKh6FYXQ',
    appId: '1:147455817597:ios:d9e531b8bd115b8b26be14',
    messagingSenderId: '147455817597',
    projectId: 'koo-pai',
    storageBucket: 'koo-pai.appspot.com',
    iosBundleId: 'com.example.app1623',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJOlVYR2Fn0GlYBqhbbYv363STKh6FYXQ',
    appId: '1:147455817597:ios:d9e531b8bd115b8b26be14',
    messagingSenderId: '147455817597',
    projectId: 'koo-pai',
    storageBucket: 'koo-pai.appspot.com',
    iosBundleId: 'com.example.app1623',
  );
}
